
# EXTM3U

english = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/english.txt'
hour24 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/24-7.txt'
kids = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/kids.txt'
sports = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/sports.txt'
news = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/news.txt'
music = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/music.txt'
adult = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/adult.txt'
movies = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/movies.txt'
pluto = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/pluto.txt'
testing = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/testing.txt'

click_4k_2019 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/2019.txt'
click_4k_2018 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/2018.txt'
click_4k_2017 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/2017.txt'
click_4k_2016 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/2016.txt'
click_4k_2015 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/2015.txt'
click_4k_2014 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/2014.txt'
click_4k_1995 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/1995.txt'
click_4k_1993 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/1993.txt'

click_1080p_2019 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2019.txt'
click_1080p_2018 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2018.txt'
click_1080p_2017 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2017.txt'
click_1080p_2016 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2016.txt'
click_1080p_2015 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2015.txt'
click_1080p_2013 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2013.txt'
click_1080p_2012 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2012.txt'
click_1080p_2011 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2011.txt'
click_1080p_1991 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/1991.txt'
click_1080p_1982 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/1982.txt'

click_720_2019 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2019.txt'
click_720_2018 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2018.txt'
click_720_2017 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2017.txt'
click_720_2016 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2016.txt'
click_720_2014 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2014.txt'
click_720_2002 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2002.txt'

theater = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/theater.txt'

vod_movies = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/vod_movies.txt'
vod_shows = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/vod_shows.txt'

kids_movies = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/kidsmovies.txt'

iiid_movies = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/3dmovies.txt'

smallville1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/smallville/smallville1.txt'
smallville2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/smallville/smallville2.txt'
smallville3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/smallville/smallville3.txt'

angermanagment = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/angermanagment.txt'

chicago_pd1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/chicago_pd/season1.txt'
chicago_pd2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/chicago_pd/season2.txt'
chicago_pd3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/chicago_pd/season3.txt'
chicago_pd4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/chicago_pd/season4.txt'
chicago_pd5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/chicago_pd/season5.txt'
chicago_pd6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/chicago_pd/season6.txt'

familyguy1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season1.txt'
familyguy2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season2.txt'
familyguy3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season3.txt'
familyguy4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season4.txt'
familyguy5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season5.txt'
familyguy6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season6.txt'
familyguy7 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season7.txt'
familyguy8 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season8.txt'
familyguy9 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season9.txt'
familyguy10 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season10.txt'
familyguy11 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season11.txt'
familyguy12 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season12.txt'
familyguy13 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season13.txt'
familyguy17 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/season17.txt'

simpsons29 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/simpsons/simpsons29.txt'
simpsons30 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/simpsons/simpsons30.txt'

supernatural1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season1.txt'
supernatural2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season2.txt'
supernatural3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season3.txt'
supernatural4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season4.txt'
supernatural5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season5.txt'
supernatural6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season6.txt'
supernatural7 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season7.txt'
supernatural8 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season8.txt'
supernatural9 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season9.txt'
supernatural10 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season10.txt'
supernatural11 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season11.txt'
supernatural12 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season12.txt'
supernatural13 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season13.txt'

stargate1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season1.txt'
stargate2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season2.txt'
stargate3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season3.txt'
stargate4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season4.txt'
stargate5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season5.txt'
stargate6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season6.txt'
stargate7 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season7.txt'
stargate8 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season8.txt'
stargate9 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season9.txt'
stargate10 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/stargate_sg1/season10.txt'

housemd1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/house/season1.txt'
housemd2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/house/season2.txt'
housemd3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/house/season3.txt'
housemd4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/house/season4.txt'
housemd5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/house/season5.txt'
housemd6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/house/season6.txt'
housemd7 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/house/season7.txt'
housemd8 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/house/season8.txt'

izombie1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/izombie/season1.txt'
izombie2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/izombie/season2.txt'
izombie3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/izombie/season3.txt'
izombie4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/izombie/season4.txt'
izombie5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/izombie/season5.txt'

ballers1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/ballers/season1.txt'
ballers2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/ballers/season2.txt'
ballers3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/ballers/season3.txt'
ballers4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/ballers/season4.txt'

designated_survivor1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/designated_survivor/season1.txt'
designated_survivor2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/designated_survivor/season2.txt'

murder_she_wrote1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/murder_she_wrote/season1.txt'
murder_she_wrote2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/murder_she_wrote/season1.txt'
murder_she_wrote3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/murder_she_wrote/season1.txt'

twilight1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/twilight/season1.txt'

star_trek_dis1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/star_trek_discovery/season1.txt'
star_trek_dis2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/star_trek_discovery/season2.txt'

lie_to_me1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/lie_to_me/season1.txt'
lie_to_me2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/lie_to_me/season2.txt'
lie_to_me3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/lie_to_me/season3.txt'

the_office1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_office/season1.txt'
the_office2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_office/season2.txt'
the_office3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_office/season3.txt'
the_office4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_office/season4.txt'
the_office5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_office/season5.txt'
the_office6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_office/season6.txt'
the_office7 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_office/season7.txt'
the_office8 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_office/season8.txt'
the_office9 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_office/season9.txt'

arrow1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/arrow/season1.txt'
arrow2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/arrow/season2.txt'
arrow3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/arrow/season3.txt'
arrow4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/arrow/season4.txt'
arrow5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/arrow/season5.txt'
arrow6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/arrow/season6.txt'
arrow7 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/arrow/season7.txt'

new_girl1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/new_girl/season1.txt'
new_girl2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/new_girl/season2.txt'
new_girl3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/new_girl/season3.txt'
new_girl4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/new_girl/season4.txt'
new_girl5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/new_girl/season5.txt'
new_girl6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/new_girl/season6.txt'

suits1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/suits/season1.txt'
suits2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/suits/season2.txt'
suits3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/suits/season3.txt'
suits4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/suits/season4.txt'
suits5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/suits/season5.txt'
suits6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/suits/season6.txt'
suits7 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/suits/season7.txt'
suits8 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/suits/season8.txt'

the_flash1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_flash/season1.txt'
the_flash2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_flash/season2.txt'
the_flash3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_flash/season3.txt'
the_flash4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_flash/season4.txt'
the_flash5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/the_flash/season5.txt'

married_with_chidren1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/married_with_children/season1.txt'
married_with_chidren2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/married_with_children/season2.txt'
married_with_chidren3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/married_with_children/season3.txt'
married_with_chidren4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/married_with_children/season4.txt'

Afghanistan = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Afghanistan.txt'
Albania = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Albania.txt'
Algeria = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Algeria.txt'
Argentina = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Argentina.txt'
Armenia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Armenia.txt'
Australia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Australia.txt'
Austria = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Austria.txt'
Azerbaijan = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Azerbaijan.txt'
Bahrain = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Bahrain.txt'
Bangladesh = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Bangladesh.txt'
Barbados = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Barbados.txt'
Belarus = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Belarus.txt'
Belgium = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Belgium.txt'
Bolivia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Bolivia.txt'
Bosnia_and_Herzegovina = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Bosnia_and_Herzegovina.txt'
Brazil = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Brazil.txt'
Bulgaria = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Bulgaria.txt'
Cambodia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Cambodia.txt'
Canada = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Canada.txt'
Chile = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Chile.txt'
China = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/China.txt'
Colombia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Colombia.txt'
Costa_Rica = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Costa_Rica.txt'
Croatia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Croatia .txt'
Cuba = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Cuba .txt'
Cyprus = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Cyprus.txt'
Czech_Republic = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Czech_Republic.txt'
Democratic_Republic_of_the_Congo = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Democratic_Republic_of_the_Congo.txt'
Denmark = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Denmark.txt'
Dominican_Republic = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Dominican_Republic.txt'
Ecuador = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Ecuador.txt'
Egypt = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Egypt.txt'
El_Salvador = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/El_Salvador.txt'
Equatorial_Guinea = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Equatorial_Guinea.txt'
Estonia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Estonia.txt'
Finland = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Finland.txt'
France = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/France.txt'
Georgia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Georgia.txt'
Germany = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Germany.txt'
Ghana = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Ghana.txt'
Greece = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Greece.txt'
Guatemala = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Guatemala.txt'
Guinea = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Guinea.txt'
Guyana = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Guyana.txt'
Haiti = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Haiti.txt'
Honduras = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Honduras.txt'
Hong_Kong = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Hong_Kong.txt'
Iceland = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Iceland.txt'
India = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/India.txt'
Indonesia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Indonesia.txt'
Iran = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Iran.txt'
Iraq = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Iraq.txt'
Ireland = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Ireland.txt'
Israel = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Israel.txt'
Italy = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Italy.txt'

Mexico = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Mexico.txt'
Russia = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Russia.txt'
Spain = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/Spain.txt'
uk = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/foreign_channels/United_Kingdom.txt'
