
# EXTM3U

english = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/english.txt'
hour24 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/24-7.txt'
kids = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/kids.txt'
sports = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/sports.txt'
news = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/news.txt'
music = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/music.txt'
adult = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/adult.txt'
movies = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/movies.txt'
pluto = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/pluto.txt'
testing = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/testing.txt'

click_4k_2019 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/2019.txt'
click_4k_2018 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/2018.txt'
click_4k_2017 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/2017.txt'
click_4k_1993 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/4k/1993.txt'

click_1080p_2019 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2019.txt'
click_1080p_2018 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2018.txt'
click_1080p_2017 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2017.txt'
click_1080p_2016 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2016.txt'
click_1080p_2015 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2015.txt'
click_1080p_2013 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2013.txt'
click_1080p_2012 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2012.txt'
click_1080p_2011 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/1080/2011.txt'

click_720_2019 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2019.txt'
click_720_2018 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2018.txt'
click_720_2017 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2017.txt'
click_720_2016 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2016.txt'
click_720_2014 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/720/2014.txt'

theater = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/theater.txt'

vod_movies = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/vod_movies.txt'
vod_shows = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/vod_shows.txt'

kids_movies = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/kidsmovies.txt'

smallville1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/smallville/smallville1.txt'
smallville2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/smallville/smallville2.txt'
smallville3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/smallville/smallville3.txt'

angermanagment = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/angermanagment.txt'

familyguy1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy1.txt'
familyguy2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy2.txt'
familyguy3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy3.txt'
familyguy4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy4.txt'
familyguy5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy5.txt'
familyguy6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy6.txt'
familyguy7 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy7.txt'
familyguy8 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy8.txt'
familyguy9 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy9.txt'
familyguy10 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy10.txt'
familyguy11 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy11.txt'
familyguy12 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy12.txt'
familyguy13 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy13.txt'
familyguy17 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/family_guy/familyguy17.txt'

simpsons29 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/simpsons/simpsons29.txt'
simpsons30 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/simpsons/simpsons30.txt'

supernatural1 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season1.txt'
supernatural2 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season2.txt'
supernatural3 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season3.txt'
supernatural4 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season4.txt'
supernatural5 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season5.txt'
supernatural6 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season6.txt'
supernatural7 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season7.txt'
supernatural8 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season8.txt'
supernatural9 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season9.txt'
supernatural10 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season10.txt'
supernatural11 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season11.txt'
supernatural12 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season12.txt'
supernatural13 = 'https://raw.githubusercontent.com/Tempest0580/Temptv/master/lists/shows/supernatural/season13.txt'

uk = 'https://raw.githubusercontent.com/freearhey/iptv/master/channels/uk.m3u'
